### PR TITLE
CXX-89 Make MingW64 work

### PR DESCRIPTION
**Pull request by Climax777**
[CXX_89] Changes to SCons files and minor changes to source files produces a
working mingw64 build of client driver.

msys with mingw64: g++.exe (x86_64-win32-seh, Built by MinGW-W64 project) 4.8.2
boost (1.55) build options: b2 toolset=gcc address-model=64 variant=release link=shared,static threadapi=win32 threading=multi runtime-link=shared -j 4 --prefix=/usr/local/ install
scons build options: scons --cxx=`which g++` --mingw --boost-postfix=-mgw48-mt-1_55 --ssl --sharedclient --prefix=/usr/local/ -j 4 install-mongoclient

Caveats: example builds fail during sharedlibrary build

### CODE REVIEW

**Comment by acmorrow** [comment]
@Climax777 If you can build the driver natively and install the DLL, and you can consume that DLL within MinGW, why is it necessary to be able to build it within MinGW?

**Comment by Climax777** [comment]
Because the ABI differs between compilers for C++ (especially 11) doesn't
it? I might be paranoid though.

I like having the same tool chain used for all my project's dependencies.
Also it is convenient for cross compiling. Most, if not all, of my projects
are cross platform. Using the same tool chain makes this a whole lot
easier. Linux is only gcc (or clang).

Have a look at Qt's guide to building with Mingw64 (don't have the link
now). They recommend using the same tool chain for the dependencies.

You will notice with my changes (albeit old) are minimal to support Mingw64.

Also a side note, a lot of growth in the msys tools has been happening.
Supporting this environment is beneficial. One could even package the
driver for the msys package manager.

**Comment by acmorrow** [comment]
@Climax777 - Yes, you are probably right about the ABI issue. That makes me slightly less disinclined to  add support for MinGW, but overall, I'm still not very excited about doing it.

That said, if we decide to move forward with it, I think it can be considerably simplified. At the very least, a start would be to rebase it onto the HEAD of the legacy branch. I think several of the things that you are doing are no longer necessary there.

**Comment by Climax777** [comment]
I agree. I will have a look this weekend from scratch and see what happens.
Perhaps support had been creeping in unbeknownst.

Thanks for considering this.

**Comment by kikop11** [comment]
hello,
on Windows platform,
who can tell me how to change the original documents in mongo-cxx-driver-legacy: SConstruct,it only support MSVC
using scons with the MinGW compiler,compile mongodb dynamic library
I want using Qt connect Mongodb c++ driver

**Comment by acmorrow** [comment]
Hi -

The legacy C++ driver does not support MinGW. However, the new C++11 likely
does, since it is a simple wrapper around the C driver, which explicitly
supports MinGW. You can find the new C++11 driver on the master branch of
the mongo-cxx-driver repo:
https://github.com/mongodb/mongo-cxx-driver/tree/master

Thanks,
Andrew

**Comment by kikop11** [comment]
Hi, is it suit for Make MingW32 work?

**Comment by acmorrow** [comment]
Hi @kikop11 - I do not believe this PR will work. I had at one point asked @Climax777 to rebase and update this PR so we could see if it could get merged, but as far as I can tell that has not happened.

MinGW support for the legacy driver is not a priority. If you are just starting out, please use the C++11 driver, found on the master branch, instead.

**Comment by Climax777** [comment]
Sorry I still haven't gotten to it yet. I'm struggling to find the time.

It shouldn't be too hard to get it updated and working on the HEAD again.
It was mostly a few standard library functions that worked differently on
MSVC vs Mingw64. And also some scons changes.

Don't give up on this yet...

**Comment by kikop11** [comment]
who can tell me,how to compile mongo-cxx-driver-master on windows?

**Comment by kikop11** [comment]
who can tell me,how to compile mongo-cxx-driver-master on windows?
I want to get a detail Compile step.

**Comment by acmorrow** [comment]
Please see my answer here: https://github.com/mongodb/mongo-cxx-driver/pull/350

**Comment by kikop11** [comment]
1.who can tell me,how to compile mongo-cxx-driver-master on windows, not using msvs compiler?
I want to get a detail Compile step using mingw32 compiler.
2.and who can tell me how to connect mongodb using qt on windows
thanks

**Comment by acmorrow** [comment]
@kikop11 - I see. Honestly you may be the first to attempt it. I don't personally know a lot about MinGW. However, in principle if you have CMake the process should be much like any other UNIX like platform:

- Build the C driver
- Configure the C++11 driver against the C driver with CMake. You can specify the compiler to CMake with -DCMAKE_C_COMPILER=/path/to/gcc-like -DCMAKE_CXX_COMPILER=/path/to/g++-like.
- Run 'make install'

**Comment by kikop11** [comment]
Hello, build the C driver success,I'm trying to build the C++ driver, from mongo-cxx-driver-master.zip. I'm on Windows 7, 64-bit Intel, with mingw492_32. I run cmake gui configure,error like:

  

CMake Error at E:/MongodbMaster/cmake-3.5.2-win32-x86/cmake-3.5.2-win32-x86/share/cmake-3.5/Modules/ExternalProject.cmake:1757 (message):
error: could not find git for clone of EP_mnmlstc_core
Call Stack (most recent call first):
E:/MongodbMaster/cmake-3.5.2-win32-x86/cmake-3.5.2-win32-x86/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
src/bsoncxx/third_party/CMakeLists.txt:19 (ExternalProject_Add)
Configuring incomplete, errors occurred!

Can you tell me what I need to install? Thanks!

**Comment by acmorrow** [comment]
@kikop11 - Please see my response to your duplicate of this question in #350. Also, please stop posting questions to PRs - that isn't what they are for. If you have questions about how to build the C++11 driver or need help, please subscribe to and post your questions to mongodb-user:

https://groups.google.com/forum/#!forum/mongodb-user

**Comment by jrassi** [comment]
I'm closing this pull request.  We've transitioned development on the legacy driver to maintenance-only work and are only planning on shipping critical bug fixes at this point; as such, we won't be adding support for new toolchains.  Thanks again, @Climax777, for the work you've done on this pull request thus far.

I've removed the "legacy-cxx" label from the linked ticket (CXX-89) and updated its title, to reflect its new focus of official support for MinGW on the master branch.

**Pull request closed without merging**
