### PR TITLE
minor: fixup clang compile

### PR DESCRIPTION
**Pull request by yongjincho**
I am using clang as a C++ compiler on OSX. However, the master branch is uncompilable because of some missing header files. I added them and would like to merge these minor changes into the upstream.

### CODE REVIEW

**Comment by acmorrow** [comment]
Thanks @yongjincho, this LGTM. Could you please amend the commit to reference ticket https://jira.mongodb.org/browse/CXX-838 in the style of our commit messages? Also, please sign the MongoDB contributor agreement so we can merge your change (see https://www.mongodb.com/legal/contributor-agreement). Thanks!

**Comment by acmorrow** [comment]
@yongjincho - Apologies, please reference ticket https://jira.mongodb.org/browse/CXX-836

**Comment by yongjincho** [comment]
@acmorrow Thanks to your response. I've been amended the commit message to refer the ticket CXX-836. I also signed the agreement. :)

**Comment by acmorrow** [comment]
Merged in 07d4243445b5f0f333bf0ee9b3f482e74adf67a4

**Pull request closed without merging**
