### PR TITLE
minor: use a newer PPA for Cmake

### PR DESCRIPTION
**Pull request by acmorrow**

### CODE REVIEW

**Comment by mbroadst** [comment]
@acmorrow there is a preferred form of installing these packages described [here](https://docs.travis-ci.com/user/installing-dependencies/)

```
addons:
  apt:
    packages:
    - cmake
    - time
```

or for PPAs:
```
addons:
  apt:
    sources:
    - deadsnakes
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
      key_url: 'https://packagecloud.io/gpg.key'
```

**Comment by acmorrow** [comment]
I'm still queueing up some things here. I wanted to make this a PR so I can ensure that Travis is doing the right thing for PRs. Once I've got it working, I'll squash it and set you as a reviewer.

**Comment by mbroadst** [comment]
@acmorrow ah okay, got it

**Comment by acmorrow** [comment]
@mbroadst - OK this is green on travis now. I'm sure there are better ways to make some of this happen, but lets tackle that in follow-on work. I'd like us to have a green baseline against which to work.

Once we are happy with this, I will backport these changes to the releases/v3.0 and releases/v3.1 branches too.

**Comment by acmorrow** [comment]
Ping @mbroadst

**Comment by mbroadst** [comment]
LGTM as long as we're agreed that this was just getting it working again, I think we can make a lot of improvements to the travis configuration but understand we are pressed for time at the moment.

**Comment by acmorrow** [comment]
@mbroadst Thanks for the review. I agree that further improvements are needed.

**Comment by acmorrow** [comment]
Commited as ef312b219bbed829813c79f6bc445b588e8c0750

**Pull request closed without merging**
