### PR TITLE
Fix rpm-package-build task

### PR DESCRIPTION
**Pull request by rcsanchez97**
Task-specific Evergreen patch build: https://spruce.mongodb.com/version/65986bbec9ec44bb3305b63b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

@kevinAlbs I am requesting your review on this since the biggest change here is a modified cherry-pick of [this commit](https://github.com/mongodb/mongo-c-driver/commit/2bf9d591d63dfc079ce7319d570dcbf0b4bdbac4) that you authored.

### CODE REVIEW

**Comment by rcsanchez97** [comment]
Also, I'd like to cherry-pick this to `releases/v3.9` after merging.

**Comment by kevinAlbs** [comment]
The patch attached to the PR [failed](https://spruce.mongodb.com/task/cxx_driver_packaging_rpm_package_build_patch_8e86136de4ae61f65995adec7eb8ff2775148e9e_6598742ba4cf47c9e3cfbb07_24_01_05_21_27_12/logs?execution=0):

```
[2024/01/05 16:32:14.378] ERROR: Command failed:
[2024/01/05 16:32:14.378]  # /usr/bin/dnf-3 --installroot /var/lib/mock/fedora-rawhide-aarch64/root/ --releasever 40 --setopt=deltarpm=False --setopt=allow_vendor_change=yes --allowerasing --disableplugin=local --disableplugin=spacewalk --disableplugin=versionlock install rpmdevtools git rpm-build cmake libutf8proc-devel boost-devel openssl-devel cyrus-sasl-devel libbson-devel mongo-c-driver-devel snappy-devel gcc-c++ libzstd-devel
```

Is that expected to be resolved after merging?

**Comment by rcsanchez97** [comment]
I am actually not sure why it succeeded in my manual patch build but is failing now in the triggered patch build. I'm trying to see if I can work out the precise cause.

**Comment by rcsanchez97** [comment]
@kevinAlbs I'm still not entirely sure why it failed, because I would have expected it to be only about the version number in the spec file, but I also had to adjust the dependencies as well. Either way, it's ready for review now.

**Review by kevinAlbs — APPROVED** [review]

**Pull request merged**
