### PR TITLE
skip empty documents when converting to json

### PR DESCRIPTION
**Pull request by yhager**

### CODE REVIEW

**Comment by acmorrow** [comment]
Thanks for the PR @yhager  Could you please open an associated ticket in the CXX project?

**Comment by acmorrow** [comment]
@hanumantmk PTAL

**Comment by acmorrow** [comment]
@yhager Is this still required? Can you write a test to demonstrate the issue that this resolves?

**Comment by acmorrow** [comment]
@yhager @hanumantmk Should I close this PR?

**Comment by yhagerjs** [comment]
Ugh, sorry, I've been busy. I'll try to finish it next week.

**Comment by acmorrow** [comment]
@yhagerjs OK FYI we are hoping to ship the stable GA (3.0.0) of the driver this week, so if there is any way you can let us know either way sooner it would be a help. Otherwise, if this is still an issue, it will slip to 3.0.1

**Comment by acmorrow** [comment]
Closing due to lack of follow-up

**Pull request closed without merging**
