### PR TITLE
CXX-817 Improve bsoncxx polyfill options handling

### PR DESCRIPTION
**Pull request by acmorrow**
Make it easier to select the other polyfills by not needing to explicitly disable mnmlstc at the same time. Also validate that the combination of options is sensible.

### CODE REVIEW

**Comment by samantharitter** [comment]
A question about one of the polyfill flags, otherwise LGTM

**Comment by acmorrow** [comment]
@samantharitter - It seemed to make the state space of options larger for no real gain. I would have needed to validate more combinations of options. This way, it just is 'on', unless you take an action that makes it be implicitly off.

**Comment by tessavitabile** [comment]
LGTM. 

One thing I find confusing about the options is that if I run cmake -DBSONCXX_POLY_USE_BOOST=ON, then I run cmake -DBSONCXX_POLY_USE_STD_EXPERIMENTAL=ON, the second time both will be on. The options aren't reset to their defaults each time you run cmake.

**Comment by acmorrow** [comment]
I suspect we are supposed to be using `cmake_dependent_option`.

**Comment by acmorrow** [comment]
@tessavitabile @samantharitter - I updated this, PTAL. I added two new commits. The first improves how the boost header search path is propagated when using boost, and the second fixes two compile issues when using the stdx::experimental polyfills.

**Comment by tessavitabile** [comment]
I don't totally understand, but nothing looks glaringly wrong, so LGTM. I guess we use emplace to set string_views.

**Comment by acmorrow** [comment]
It seems that in std::experimental::optional, the templated operator= only works if U can decay to T. In our case, it can't. Using emplace works everywhere though.

**Comment by acmorrow** [comment]
As for the CMake stuff, yeah, I wouldn't worry too much about it.

**Comment by samantharitter** [comment]
still LGTM

**Pull request merged**
