### PR TITLE
CXX-911 Add clang-format version check

### PR DESCRIPTION
**Pull request by xdg**
This commit adds the same version check as in the server build script.

Note: this only suppresses a warning if the version is correct; there is
still no assertion if the version is wrong.

### CODE REVIEW

**Comment by xdg** [comment]
@acmorrow @markbenvenuto Please take a look

**Comment by acmorrow** [comment]
LGTM

**Comment by acmorrow** [comment]
@xdg Feel free to get this committed, with a reminder that we use a rebase workflow to keep a linear history, so please don't just hit the merge button.

**Comment by acmorrow** [comment]
@markbenvenuto Is this also an issue in the server repo copy of this? Or was it fixed there but never backported?

**Comment by xdg** [comment]
@acmorrow The merge button is evil.  I wish GH would let repo admins turn it off.

**Comment by xdg** [comment]
Rebased to master as 86738ee

**Pull request closed without merging**
