### PR TITLE
CXX-666 Backport server r3.0.6..r3.0.7 changes to the legacy driver

### PR DESCRIPTION
**Pull request by acmorrow**
Server SHAs

447aa61
946c96a

See CXX-666 for details on why these commits.

### CODE REVIEW

**Comment by markbenvenuto** [comment]
There are three commits in this pull request. The change to the SSL manager is not listed in your pull request description or in the bug as non-strikethrough.

**Comment by acmorrow** [comment]
@markbenvenuto Thanks - good catch. That came from a commit that I picked in, but then got reverted. Apparently I committed the pick but not the revert and didn't squash it out.

**Comment by acmorrow** [comment]
@markbenvenuto updated, PTAL

**Comment by markbenvenuto** [comment]
:+1:

**Pull request merged**
