### PR TITLE
Documentation edits

### PR DESCRIPTION
**Pull request by samantharitter**

### CODE REVIEW

**Comment by samantharitter** [comment]
@TylerBrock sorry it wrote over your comments on the old diff, but I believe this version addresses them all!

**Comment by TylerBrock** [comment]
Looks good, I merged it in. You had an extra file "src/mongo/integration/standalone/server.log"

**Comment by acmorrow** [comment]
Is this PR dead?

**Comment by TylerBrock** [comment]
It was merged in. We can close.

**Pull request closed without merging**
