### PR TITLE
CXX-902 Reduce flushes on output operations...

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
## Changes
* Replaced `std::endl` for `\n` to adhere to the [CPP Core Guildelines](https://github.com/isocpp/CppCoreGuidelines) @ `Guideline SL.50`

### CODE REVIEW

**Comment by acmorrow** [comment]
LGTM. Thanks for the PR. We will get this merged.

How did we do w.r.t. the other CPP Core Guidelnes, out of curiosity?

**Comment by RicoAntonioFelix** [comment]
> How did we do w.r.t. the other CPP Core Guidelnes, out of curiosity?

I'm still slowly going through the codebase manually as tools for checking code against the CPP Core Guidelines are still a WIP...

I'm basically doing this as I'm trying to figure out the best way to integrate `MongoDB` into our [project](https://github.com/hioa-cs/IncludeOS) as its one of the items on the [roadmap](https://github.com/hioa-cs/IncludeOS/wiki/Roadmap)...

**Comment by acmorrow** [comment]
Very interesting. Would you mind signing the MongoDB contributor agreement and I will get this in?

https://www.mongodb.com/legal/contributor-agreement

**Comment by RicoAntonioFelix** [comment]
Done...

**Comment by acmorrow** [comment]
@RicoAntonioFelix merged, thank you for the improvement!

**Comment by RicoAntonioFelix** [comment]
:+1:

**Pull request merged**
