### PR TITLE
CXX-662 remove extra semicolons after _ATOMIC_WORD_DECLARE

### PR DESCRIPTION
**Pull request by amidvidy**

### CODE REVIEW

**Comment by markbenvenuto** [comment]
:+1:

**Comment by acmorrow** [comment]
Did you do a build with CCFLAGS=-pedantic-errors to verify?

Typically we try to make our macros statement like, in that you are expected to follow them with a ;, but I don't care that much in the legacy driver.

This will create a small divergence from the upstream 3.0 release code, but I don't anticipate that changing much, if at all.

So, LGTM per testing request.

**Comment by amidvidy** [comment]
it looks like we don't compile with -pedantic-errors for other reasons e.g.:
```
g++ -o build/linux2/ssl/mongo/base/string_data.o -c -Wnon-virtual-dtor -Woverloaded-virtual -pedantic-errors -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -DMONGO_HAVE___THREAD -DBOOST_THREAD_USES_DATETIME -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_POSIX_MONOTONIC_CLOCK -DMONGO_HAVE_TIMEGM -DMONGO_HAVE_FIPS_MODE_SET -DLIBMONGOCLIENT_BUILDING -DSTATIC_LIBMONGOCLIENT -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Isrc/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Isrc -Ibuild/linux2/ssl/mongo -Isrc/mongo src/mongo/base/string_data.cpp
In file included from src/mongo/base/make_string_vector.cpp:16:0:
src/mongo/base/make_string_vector.h:28:34: error: anonymous variadic macros were introduced in C++11 [-Wvariadic-macros]
 #define MONGO_MAKE_STRING_VECTOR(...) ::mongo::_makeStringVector(0, __VA_ARGS__, NULL)
                                  ^

```

**Comment by acmorrow** [comment]
Yeah, I think the point is that our headers should though. If you build with -k to get as far as possible, can you verify that all of the errors are at .cpp scope? That should be enough.

**Pull request merged**
