### PR TITLE
fix python syntax errors

### PR DESCRIPTION
**Pull request by AnonymousDeveloper4201337**
This change is [Reviewable](https://reviewable.io/reviews/mongodb/mongo-cxx-driver/593)

### CODE REVIEW

**Comment by AnonymousDeveloper4201337** [comment]
I got a syntax error using python2 before making these changes

**Comment by acmorrow** [comment]
Are you using SCons 3.0? If so, it has a bug where it enforces Python 3 print statements, even though it is supposed to admit SConscripts written in either Py2 or Py3 style.

**Comment by AnonymousDeveloper4201337** [comment]
Yea that’s why I’m commiting this fix

**Comment by AnonymousDeveloper4201337** [comment]
Parenthesis works on python 2

**Comment by derickr** [comment]
Merged into ``legacy`` after a reword of the commit message: https://github.com/mongodb/mongo-cxx-driver/commit/bdc149b8ddcca54fc4147345d005f0cd8a95d8c1

**Comment by AnonymousDeveloper4201337** [comment]
Thank you sir 👍

**Pull request closed without merging**
