### PR TITLE
CXX-2614 sync tests impacted by removal of MONGODB-CR

### PR DESCRIPTION
**Pull request by kevinAlbs**
# Summary
- Sync the tests updated in
https://github.com/mongodb/specifications/commit/735a667672c758617821e3c5dda99c551e007375

### CODE REVIEW

**Comment by eramongodb** [comment]
Should [src/libmongoc/tests/json/command_monitoring/unified/redacted-commands.json](https://github.com/mongodb/mongo-c-driver/blob/b91eea44f2fa1eb54fa6eb385214210cc46663d2/src/libmongoc/tests/json/command_monitoring/unified/redacted-commands.json) also be synced with [source/command-logging-and-monitoring/tests/monitoring/redacted-commands.json](https://github.com/mongodb/specifications/blob/735a667672c758617821e3c5dda99c551e007375/source/command-logging-and-monitoring/tests/monitoring/redacted-commands.json)?

**Comment by kevinAlbs** [comment]
> Should [src/libmongoc/tests/json/command_monitoring/unified/redacted-commands.json](https://github.com/mongodb/mongo-c-driver/blob/b91eea44f2fa1eb54fa6eb385214210cc46663d2/src/libmongoc/tests/json/command_monitoring/unified/redacted-commands.json) also be synced with [source/command-logging-and-monitoring/tests/monitoring/redacted-commands.json](https://github.com/mongodb/specifications/blob/735a667672c758617821e3c5dda99c551e007375/source/command-logging-and-monitoring/tests/monitoring/redacted-commands.json)?

Yes, that is updated in this PR: https://github.com/mongodb/mongo-c-driver/pull/1165

**Review by eramongodb — APPROVED** [review]
Confused by where the line removal diffs in `redacted-commands.json` is coming from, but otherwise LGTM.

**Comment by kevinAlbs** [comment]
> Confused by where the line removal diffs in `redacted-commands.json` is coming from, but otherwise LGTM.

The `authenticate-without-observing` test may have been added in the C++ driver when initially included by @vector-of-bool here: https://github.com/mongodb/mongo-cxx-driver/pull/803/commits/b23a3b86a66335657be7ad11a7664d2b456049f9#diff-3930ed09d0bf0a45e7af7cfab4f3f5332d34fc5ba1724185358ee83ffdee85e8R95

I want to keep the test matching the specifications. The `authenticate-without-observing` test appears to test the behavior when `observeSensitiveCommands=false`. That is also tested in the [observeSensitiveCommands tests](https://github.com/mongodb/mongo-cxx-driver/blob/0b6488fb64d8833c6fc1f791ea738a30798f2b38/data/unified-format/valid-pass/observeSensitiveCommands.json#L108).

**Pull request merged**
