### PR TITLE
ci: update windows-64 distro in configuration

### PR DESCRIPTION
**Pull request by tychoish**

### CODE REVIEW

**Comment by acmorrow** [comment]
LGTM

**Comment by acmorrow** [comment]
@tychoish You should be able to rebase and push this, btw? Or do you not have permissions here and need our team to do it?

**Comment by tychoish** [comment]
merged. (I did the cherry-pick merge, and so am closing the pr manually)

**Comment by acmorrow** [comment]
This seems to have broken compile on the legacy branch:

https://evergreen.mongodb.com/task_log_raw/mongodb_cpp_driver_windows_64_msvc2010_dbg_dyn_dyn_compile_853e43ed12209603bcfb2fc9319e6ef75ba73d64_15_10_21_21_47_41/0?type=T

Seems it can no longer find the boost headers?

**Comment by acmorrow** [comment]
@tychoish - can you close this with a ref to the appropriate commit? Thanks

**Comment by tychoish** [comment]
This issue was resolved int: 853e43ed12209603bcfb2fc9319e6ef75ba73d64

**Pull request closed without merging**
