### PR TITLE
Add OS X buildvariant

### PR DESCRIPTION
**Pull request by samantharitter**
New buildvariant, plus some refactoring of the config file to make this easier.

### CODE REVIEW

**Comment by amidvidy** [comment]
patch build?

**Comment by samantharitter** [comment]
ooh sorry forgot to leave that here yesterday https://mci.10gen.com/version/54c028433ff12268290002c9_0

The OS X buildvariant is failing its integration tests, but that's [a somewhat separate issue](https://jira.mongodb.org/browse/CXX-483).

**Comment by amidvidy** [comment]
nice, this refactor is pretty slick. LGTM with green patch build.

**Comment by samantharitter** [comment]
Thanks!

**Pull request merged**
