### PR TITLE
update google tag manager id

### PR DESCRIPTION
**Pull request by kay-kim**
I updated in master branch.  Let me know if it needs to be in the stable branch.

### CODE REVIEW

**Comment by derickr** [comment]
Hi Kay,

is this change still relevant?

cheers,
Derick

**Comment by acmorrow** [comment]
@kay-kim - What should happen with this PR? Thanks!

**Comment by kay-kim** [comment]
Yes please.  If you want the google analytics to track the c++ docs pages.

**Comment by kay-kim** [comment]
Oh, I meant, it'll need to be merged.

**Comment by kay-kim** [comment]
Oh, never mind.  David has already merged it.

**Pull request closed without merging**
