### PR TITLE
CXX-1044 collection::find should handle partial/no_timeout options

### PR DESCRIPTION
**Pull request by jrassi**

### CODE REVIEW

**Comment by jrassi** [comment]
@acmorrow @xdg, PTAL.

**Comment by acmorrow** [comment]
Code LGTM. Per discussion, I propose that we rebase this against master and commit it there, as this is a real bug in the shipping version of the driver.

**Comment by xdg** [comment]
LGTM.  I don't know if we'll ship a 3.0.3 before 3.1 but agree this should go against master and be merged/cherry-picked to 3.1-dev.

**Comment by jrassi** [comment]
Merged into master as 809aa9a.  I'll sync up 3.1-dev in the near future.

**Pull request closed without merging**
