### PR TITLE
Add empty() to bsoncxx::array::view()

### PR DESCRIPTION
**Pull request by yhager**

### CODE REVIEW

**Comment by acmorrow** [comment]
@yhager Hey, thanks for the PR. Could you open a ticket in the CXX project?

**Comment by yhagerjs** [comment]
https://jira.mongodb.org/browse/CXX-654

**Comment by yhager** [comment]
https://jira.mongodb.org/browse/CXX-654

**Comment by hanumantmk** [comment]
Thanks for the contribution!

**Pull request merged**
