### PR TITLE
CXX-821 Add links to document validation documentation

### PR DESCRIPTION
**Pull request by samantharitter**
Note: the todos related to read_concern are fixed in the read_concern pull request.

### CODE REVIEW

**Comment by acmorrow** [comment]
These changes look good. However, I think there are some other "link to docs" todos client/collection/database, mostly about read_concern

**Comment by acmorrow** [comment]
Also the read_concern class itself

**Comment by samantharitter** [comment]
Right, the read_concern ones are addressed in the read_concern pull request.  I don't think there were any others besides read_concern, did you find any?

**Comment by acmorrow** [comment]
Oh, sorry. I hadn't looked at that one so didn't notice you had picked them up yet. LGTM then

**Pull request merged**
