### PR TITLE
CXX-500 Only start mongo-orchestration from Scons when running examples

### PR DESCRIPTION
**Pull request by acmorrow**
This isn't pretty, but it gets rid of the annoying startup warnings and and delay when running things that aren't the examples.

### CODE REVIEW

**Comment by amidvidy** [comment]
can you put up a patch build?

**Comment by acmorrow** [comment]
@amidvidy https://evergreen.mongodb.com/version/551ae9b73ff122135600089f_0

**Comment by acmorrow** [comment]
Updated with a fix for the windows build variant failures. Still not clear on what is causing problems with the integration test suites: this shouldn't have affected it.

**Comment by acmorrow** [comment]
@amidvidy given the M-O issues, should we go ahead with this? The client tests seem to be working fine.

**Comment by amidvidy** [comment]
LGTM.

**Pull request merged**
